// runtime.c — UNC runtime shim
// Handles model loading, token loop, and sampling.

#include "runtime.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <math.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>

// Forward declarations for functions generated by unc (filled in after compilation)
extern void unc_init(const char* metallib_path, void* weight_data, size_t weight_size);
extern void unc_forward(
    const uint32_t* token_ids,
    uint32_t        seq_len,
    uint32_t        total_seq_len,
    float*          out_logits
);

// ---------------------------------------------------------------------------
// Runtime struct
// ---------------------------------------------------------------------------

struct UNCRuntime {
    // Memory-mapped weight file
    int     weight_fd;
    void*   weight_data;
    size_t  weight_size;

    // Model config (populated from .unc header)
    uint32_t vocab_size;
    uint32_t max_seq_len;

    // Logit buffer (re-used each step)
    float* logit_buf;
};

// ---------------------------------------------------------------------------
// Sampling
// ---------------------------------------------------------------------------

static uint32_t sample_greedy(const float* logits, uint32_t vocab_size) {
    uint32_t best = 0;
    float best_val = logits[0];
    for (uint32_t i = 1; i < vocab_size; i++) {
        if (logits[i] > best_val) {
            best_val = logits[i];
            best = i;
        }
    }
    return best;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

UNCRuntime* unc_load(const char* unc_path) {
    UNCRuntime* rt = (UNCRuntime*)calloc(1, sizeof(UNCRuntime));
    if (!rt) return NULL;

    // Open and mmap the .unc file (weight data section)
    rt->weight_fd = open(unc_path, O_RDONLY);
    if (rt->weight_fd < 0) {
        perror("unc_load: open");
        free(rt);
        return NULL;
    }

    struct stat st;
    fstat(rt->weight_fd, &st);
    rt->weight_size = (size_t)st.st_size;

    rt->weight_data = mmap(NULL, rt->weight_size, PROT_READ, MAP_SHARED, rt->weight_fd, 0);
    if (rt->weight_data == MAP_FAILED) {
        perror("unc_load: mmap");
        close(rt->weight_fd);
        free(rt);
        return NULL;
    }

    // TODO: parse .unc header to extract vocab_size, max_seq_len, metallib_path
    rt->vocab_size  = 128256; // LLaMA-3 default — will be read from header
    rt->max_seq_len = 8192;

    rt->logit_buf = (float*)malloc(rt->vocab_size * sizeof(float));

    // TODO: find metallib path from .unc header
    // unc_init("<metallib_path>", rt->weight_data, rt->weight_size);

    fprintf(stderr, "unc_load: loaded %zu bytes from %s\n", rt->weight_size, unc_path);
    return rt;
}

void unc_generate(
    UNCRuntime*  rt,
    const char*  prompt,
    int          max_tokens,
    char*        out_buf,
    size_t       out_size
) {
    if (!rt || !prompt) return;

    // TODO: tokenize prompt using bundled tokenizer
    // For now, use a placeholder token sequence
    uint32_t token_ids[1] = {1}; // BOS token
    uint32_t seq_len = 1;

    out_buf[0] = '\0';
    size_t out_pos = 0;

    for (int step = 0; step < max_tokens; step++) {
        uint32_t total_seq = seq_len;
        unc_forward(token_ids, seq_len, total_seq, rt->logit_buf);

        uint32_t next_token = sample_greedy(rt->logit_buf, rt->vocab_size);

        // EOS check
        if (next_token == 2) break; // EOS id = 2 for most models

        // TODO: detokenize and append to output
        if (out_pos + 8 < out_size) {
            int written = snprintf(out_buf + out_pos, out_size - out_pos, "[%u]", next_token);
            if (written > 0) out_pos += written;
        }

        token_ids[0] = next_token;
        seq_len = 1; // decode mode after first step
    }
}

void unc_serve(UNCRuntime* rt, int port) {
    (void)rt;
    fprintf(stderr, "unc_serve: HTTP server on port %d (not yet implemented)\n", port);
}

void unc_free(UNCRuntime* rt) {
    if (!rt) return;
    if (rt->weight_data && rt->weight_data != MAP_FAILED) {
        munmap(rt->weight_data, rt->weight_size);
    }
    if (rt->weight_fd >= 0) {
        close(rt->weight_fd);
    }
    free(rt->logit_buf);
    free(rt);
}
